# Generated by Django 5.1.2 on 2024-10-15 16:09

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=64)),
                ('provider_name', models.CharField(max_length=124)),
                ('apn', models.CharField(max_length=64)),
                ('iccid', models.CharField(max_length=100)),
                ('check_usage', models.CharField(default='n/a', max_length=200)),
                ('ip_breakout', models.CharField(default='n/a', max_length=100)),
                ('topup_eligibility', models.CharField(max_length=500)),
                ('esim_status', models.CharField(default='n/a', max_length=255)),
                ('activation', models.CharField(default='n/a', max_length=1000)),
                ('replacement', models.CharField(default='n/a', max_length=1000)),
                ('cancellation', models.CharField(default='n/a', max_length=1000)),
                ('pkg_change', models.CharField(default='n/a', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('kyc_policy', models.CharField(max_length=1000)),
                ('networks', models.ManyToManyField(to='providers.network')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.operator')),
            ],
        ),
    ]
