# Generated by Django 5.1.2 on 2024-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='replacement',
            new_name='esim_replacement',
        ),
        migrations.AddField(
            model_name='operator',
            name='admin_refund_method',
            field=models.CharField(default='n/a', max_length=1000),
        ),
        migrations.AddField(
            model_name='operator',
            name='call_min',
            field=models.CharField(default='n/a', max_length=500),
        ),
        migrations.AddField(
            model_name='operator',
            name='cancel_if_activated',
            field=models.CharField(default='n/a', max_length=1000),
        ),
        migrations.AddField(
            model_name='operator',
            name='contact_list',
            field=models.CharField(default='n/a', max_length=500),
        ),
        migrations.AddField(
            model_name='operator',
            name='contact_notes',
            field=models.CharField(default='n/a', max_length=1000),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone_no',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='operator',
            name='second_tier_notes',
            field=models.CharField(default='n/a', max_length=1000),
        ),
    ]
