# Generated by Django 5.1.2 on 2024-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_replacement_operator_esim_replacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='contact_list',
            field=models.TextField(default='n/a', max_length=500),
        ),
    ]
