# Generated by Django 5.1.2 on 2024-10-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
