# Generated by Django 5.1.2 on 2024-10-21 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_rename_topic_id_case_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='case_id',
        ),
        migrations.AddField(
            model_name='resolution',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.case'),
            preserve_default=False,
        ),
    ]
