# Generated by Django 5.1.2 on 2024-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_remove_resolution_case_id_resolution_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='name',
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolve',
            field=models.TextField(default='n/a', max_length=3000),
            preserve_default=False,
        ),
    ]
