# Generated by Django 5.1.2 on 2024-10-23 17:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_resolution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='resolve',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
